### PR TITLE
updated chain-making.md to 0.11.3

### PR DESCRIPTION
**Pull request by SCBuergel**
Fixed some minor issues in the chain making tutorial:
- The output of `eris services -ls` looks differently than in the tutorial.
- The `-a` flag seems to be gone, from `eris`, `eris chains` and `eris services` so I removed those sections.

### CODE REVIEW

**Comment by pietv** [comment]
@SCBuergel very sorry you bumped into it, but the documentation outlines now the thing are going to be looking after the upcoming release which is currently planned for this week. Please, kindly leave it as it is now. I'll update you when the release happens. Thanks!

**Comment by SCBuergel** [comment]
Ok I didn't know that, then let's close this PR?

**Comment by pietv** [comment]
This change looks useful, though. Thanks for that! (I can make that amendment myself, np)
```
Eris versions >= 0.11.3
```
But please do if you feel like it.

**Comment by zramsay** [comment]
ah yeah. we merged those changes before the release. the tuts have been vetted for 0.11.4, which is due for release tomorrow...

**Comment by pietv** [comment]
inserted that version bit from the PR

**Pull request closed without merging**
